import { BookMarked, Compass, Heart, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { PublicLayout } from "@/components/PublicLayout";
import { trpc } from "@/lib/trpc";

const approach = [{ icon: Compass, title: "Start with the learner’s goal", body: "Consultation and placement guidance help identify an appropriate language route before enrolment." }, { icon: BookMarked, title: "Practise actively", body: "The centre describes interactive learning supported by digital classroom tools and guided practice." }, { icon: Heart, title: "Build confidence steadily", body: "Learning pathways are designed around language development, cultural awareness and practical communication." }];

export default function About() {
  const team = trpc.content.publicTeamProfiles.useQuery();
  return <PublicLayout><div className="simple-route-page"><header className="simple-route-header"><p className="simple-eyebrow">About</p><h1>Language learning built around clear progress.</h1><p>Bilingual Idol Language Centre supports learners in Kuala Lumpur with language pathways, consultation and a focus on confident communication.</p></header><section className="simple-route-section"><div className="simple-detail-layout"><div><h2>What the centre supports</h2><p className="simple-body-copy">The centre describes a learning environment with interactive classrooms, digital learning resources, placement guidance and personalised language routes.</p></div><div><h2>How learning is supported</h2><div className="simple-approach-list">{approach.map(({ icon: Icon, title, body }) => <article key={title}><Icon size={18} /><div><strong>{title}</strong><p>{body}</p></div></article>)}</div></div></div></section><section className="simple-route-section simple-section-tint"><div className="simple-section-heading"><div><p className="simple-eyebrow">Educators</p><h2>Team information</h2></div><Link href="/contact" className="simple-text-link">Contact the centre</Link></div>{team.data?.length ? <div className="simple-team-list">{team.data.map(member => <article key={member.id}><UsersRound size={18} /><div><strong>{member.name}</strong><span>{member.role}</span><p>{member.bio}</p><small>Languages: {member.languages}</small></div></article>)}</div> : <div className="simple-empty-state"><p>Educator profiles are shown only when the centre has confirmed the information.</p></div>}</section></div></PublicLayout>;
}
