import { Clock3, Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import { CentreMap } from "@/components/CentreMap";
import { LeadForm } from "@/components/LeadForm";
import { PublicLayout } from "@/components/PublicLayout";
import { trpc } from "@/lib/trpc";

export default function Contact() {
  const settings = trpc.content.siteSettings.useQuery();
  const contactCards = [{ icon: MapPin, label: "Visit us", value: "E-03-10, StarParc Point, Jalan Genting Kelang, Taman Danau Kota, 53300, Setapak, Kuala Lumpur.", href: "https://www.google.com/maps/search/?api=1&query=E-03-10%2C+StarParc+Point%2C+Jalan+Genting+Kelang%2C+Setapak%2C+Kuala+Lumpur" }, { icon: Phone, label: "Call us", value: "+6 03 6731 0449", href: "tel:+60367310449" }, { icon: Mail, label: "Email us", value: "info@bilingualidol.edu.my", href: "mailto:info@bilingualidol.edu.my" }, { icon: Clock3, label: "Operating hours", value: settings.data?.operatingHours ?? "Operating hours will be published by the centre.", href: undefined }];
  return <PublicLayout><div className="atlas-page"><section className="atlas-page-hero"><div className="compass-shell atlas-page-hero-content py-12 sm:py-16"><div><p className="atlas-eyebrow">Contact & visits</p><h1 className="atlas-section-title !mt-4 !text-white">Start with one helpful conversation.</h1><p className="mt-5 max-w-2xl text-base leading-7">Whether you know the programme you want or simply need direction, the centre can help identify a meaningful next step.</p></div><div className="atlas-page-hero-image"><img src="/manus-storage/bilingual-idol-contact-vignette_1b87f154.jpg" alt="Teacher welcoming a learner and parent to the centre" loading="eager" /></div></div></section><section className="atlas-section"><div className="compass-shell grid gap-4 md:grid-cols-2">{contactCards.map(({ icon: Icon, label, value, href }, index) => <article key={label} className="atlas-route-card !min-h-0 !justify-start"><span className={`grid h-12 w-12 shrink-0 place-items-center rounded-full ${index === 1 ? "bg-[#f4eddd] text-[#a34732]" : "bg-[#e7f0eb] text-[#397563]"}`}><Icon size={19} /></span><div><p className="mt-6 text-[10px] font-extrabold tracking-[.11em] text-[#708098] uppercase">{label}</p>{href ? <a className="mt-2 block text-sm font-bold leading-6 text-[#29415b] hover:text-[#397563]" href={href} target={href.startsWith("http") ? "_blank" : undefined} rel={href.startsWith("http") ? "noreferrer" : undefined}>{value}</a> : <p className="mt-2 text-sm font-bold leading-6 text-[#29415b]">{value}</p>}</div></article>)}</div></section><section className="pb-16 sm:pb-20"><div className="compass-shell"><div className="compass-card overflow-hidden"><CentreMap /></div></div></section><section className="atlas-section atlas-section-paper"><div className="compass-shell atlas-form-layout"><div><p className="atlas-eyebrow">Send an inquiry</p><h2 className="atlas-section-title">Tell us what the learner needs next.</h2><p className="atlas-section-copy">For a faster response to a time-sensitive question, you can also contact the centre directly on WhatsApp.</p><a className="atlas-button-primary mt-7" href="https://wa.me/60367310449" target="_blank" rel="noreferrer"><MessageCircle size={17} /> Chat on WhatsApp</a></div><div className="atlas-form-wrap"><LeadForm type="inquiry" title="Tell us what you need" /></div></div></section></div></PublicLayout>;
}
