import { Clock3, Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import { CentreMap } from "@/components/CentreMap";
import { LeadForm } from "@/components/LeadForm";
import { PublicLayout } from "@/components/PublicLayout";
import { trpc } from "@/lib/trpc";

export default function Contact() {
  const settings = trpc.content.siteSettings.useQuery();
  const contactCards = [{ icon: MapPin, label: "Visit us", value: "E-03-10, StarParc Point, Jalan Genting Kelang, Taman Danau Kota, 53300, Setapak, Kuala Lumpur.", href: "https://www.google.com/maps/search/?api=1&query=E-03-10%2C+StarParc+Point%2C+Jalan+Genting+Kelang%2C+Setapak%2C+Kuala+Lumpur" }, { icon: Phone, label: "Call us", value: "+6 03 6731 0449", href: "tel:+60367310449" }, { icon: Mail, label: "Email us", value: "info@bilingualidol.edu.my", href: "mailto:info@bilingualidol.edu.my" }, { icon: Clock3, label: "Operating hours", value: settings.data?.operatingHours ?? "Operating hours will be published by the centre.", href: undefined }];
  return <PublicLayout><div className="compass-page"><section className="compass-paper"><div className="compass-shell grid gap-8 py-16 sm:py-20 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="compass-kicker">Contact & visits</p><h1 className="compass-display mt-5 max-w-4xl text-5xl leading-[.95] sm:text-6xl">Start with one helpful <em className="font-normal text-[#ef795b]">conversation.</em></h1><p className="mt-6 max-w-2xl text-base leading-7 text-[#53657a]">Whether you know the programme you want or simply need direction, the centre can help identify a meaningful next step.</p></div><span className="compass-page-marker">05</span></div></section><section className="compass-grid py-14 sm:py-20"><div className="compass-shell grid gap-4 md:grid-cols-2">{contactCards.map(({ icon: Icon, label, value, href }, index) => <article key={label} className="compass-card flex gap-4 p-5"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl ${index === 1 ? "bg-[#f4eddd] text-[#a34732]" : "bg-[#e7f0eb] text-[#397563]"}`}><Icon size={19} /></span><div><p className="text-[10px] font-extrabold tracking-[.11em] text-[#708098] uppercase">{label}</p>{href ? <a className="mt-2 block text-sm font-bold leading-6 text-[#29415b] hover:text-[#397563]" href={href} target={href.startsWith("http") ? "_blank" : undefined} rel={href.startsWith("http") ? "noreferrer" : undefined}>{value}</a> : <p className="mt-2 text-sm font-bold leading-6 text-[#29415b]">{value}</p>}</div></article>)}</div></section><section className="pb-16 sm:pb-20"><div className="compass-shell"><div className="compass-card overflow-hidden"><CentreMap /></div></div></section><section className="border-t border-[#ded4c2] bg-[#f4eddd] py-16 sm:py-20"><div className="compass-shell grid gap-10 lg:grid-cols-[.72fr_1.28fr]"><div><p className="compass-kicker">Send an inquiry</p><h2 className="compass-display mt-5 text-5xl leading-[.95]">Tell us what the learner needs next.</h2><p className="mt-5 max-w-md text-base leading-7 text-[#53657a]">For a faster response to a time-sensitive question, you can also contact the centre directly on WhatsApp.</p><a className="compass-btn-primary mt-7" href="https://wa.me/60367310449" target="_blank" rel="noreferrer"><MessageCircle size={17} /> Chat on WhatsApp</a></div><div className="compass-form"><LeadForm type="inquiry" title="Tell us what you need" /></div></div></section></div></PublicLayout>;
}
