import { ArrowRight, ArrowUpRight, BookOpen, Check, CircleHelp, Compass, GraduationCap, HeartHandshake, Languages, MapPin, Sparkles, Star } from "lucide-react";
import { Link } from "wouter";
import { LeadForm } from "@/components/LeadForm";
import { PublicLayout } from "@/components/PublicLayout";
import { trpc } from "@/lib/trpc";

const steps = [
  { number: "01", title: "Start with a real goal", copy: "Tell us the language, life stage, or confidence you want to build.", icon: Compass },
  { number: "02", title: "Choose a clear route", copy: "See confirmed programme details, practical timings, and the next useful action.", icon: BookOpen },
  { number: "03", title: "Keep the next move clear", copy: "Return to a clear programme route and use your private account when the centre enables it.", icon: HeartHandshake },
];

export default function Home() {
  const programs = trpc.content.publicPrograms.useQuery();
  const testimonials = trpc.content.publicTestimonials.useQuery();
  return <PublicLayout><div className="atlas-page overflow-hidden">
    <section className="atlas-hero"><img src="/manus-storage/bilingual-idol-hero-reference_4aa89f37.jpg" className="atlas-hero-media" alt="Learners and a teacher collaborating during a language activity" fetchPriority="high" /><div className="compass-shell atlas-hero-grid"><div className="atlas-hero-copy"><p className="atlas-eyebrow">Language learning, made personal</p><h1 className="atlas-hero-title">Build the confidence to <em>say more.</em></h1><p className="atlas-hero-subtitle">Clear language pathways for children, teens, adults and families — from the first conversation to confident everyday use.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/enroll" className="atlas-button-primary">Start a learning enquiry <ArrowUpRight size={17} /></Link><Link href="/programs" className="atlas-button-secondary">Explore programmes <ArrowRight size={17} /></Link></div><div className="atlas-language-strip"><span>English</span><span>Bahasa Melayu</span><span>中文</span><span>العربية</span><span>日本語</span><span>한국어</span></div></div><aside className="atlas-floating-card" aria-label="Learning pathway summary"><p>Your next step</p><strong>Tell us the language goal, age and learning rhythm.</strong><span>We will help you find a clearer route before you commit to a programme.</span></aside></div></section>

    <section className="atlas-stat-band"><div className="compass-shell"><div className="atlas-stat"><p className="atlas-stat-label">Established</p><p className="atlas-stat-value">Since 2008</p></div><div className="atlas-stat"><p className="atlas-stat-label">Based in</p><p className="atlas-stat-value">Setapak, Kuala Lumpur</p></div><div className="atlas-stat"><p className="atlas-stat-label">Built for</p><p className="atlas-stat-value">Practical confidence</p></div></div></section>

    <section className="atlas-section"><div className="compass-shell"><div className="atlas-section-grid programmes"><div><p className="atlas-eyebrow">Programme finder</p><h2 className="atlas-section-title">Choose a route that feels right for now.</h2><p className="atlas-section-copy">Filter confirmed programmes by language, level, age group and goal. Clear details first; no pressure to decide before you are ready.</p><Link href="/programs" className="atlas-button-secondary mt-7">Find a programme <ArrowRight size={17} /></Link></div><div>{programs.isLoading ? <div className="grid gap-4 sm:grid-cols-2">{[1, 2, 3, 4].map(item => <div key={item} className="skeleton-shimmer h-64 rounded-2xl" />)}</div> : programs.data?.length ? <div className="grid gap-4 sm:grid-cols-2">{programs.data.slice(0, 4).map((program, index) => <Link key={program.slug} href={`/programs/${program.slug}`} className="atlas-route-card"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-white/80 px-3 py-1 text-[10px] font-extrabold tracking-[.12em] text-[#397563] uppercase">{program.language}</span><ArrowUpRight className="text-[#397563]" size={20} /></div><div><h3>{program.title}</h3><p className="line-clamp-2">{program.description}</p><p className="mt-5 text-xs font-extrabold tracking-[.08em] text-[#397563] uppercase">{program.ageGroup} · {program.level}</p></div></Link>)}</div> : <div className="compass-empty"><Languages className="mx-auto text-[#397563]" size={30} /><h3 className="compass-display mt-4 text-3xl">Confirmed programme details are being prepared.</h3><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-[#53657a]">The centre can still help you choose a relevant next step while verified programme details are added.</p><Link href="/contact" className="atlas-button-secondary mt-6">Ask for guidance <ArrowRight size={16} /></Link></div>}</div></div></div></section>

    <section className="atlas-section atlas-section-paper"><div className="compass-shell atlas-visual-split"><div className="atlas-visual-split-media"><img src="/manus-storage/bilingual-idol-programme-vignette_4d9bc18a.jpg" alt="Learners and teacher collaborating during a language activity" loading="lazy" /></div><div className="flex flex-col justify-center"><p className="atlas-eyebrow">A simple learning rhythm</p><h2 className="atlas-section-title !mt-3 !text-white">Less searching. More learning.</h2><p className="atlas-section-copy">We make the next move clear: understand the goal, compare the relevant options, then start with confidence.</p><div className="atlas-checklist">{steps.map(({ number, title, icon: Icon }) => <span key={number}><i><Icon size={15} /></i>{title}</span>)}</div></div></div></section>

    <section className="atlas-section"><div className="compass-shell atlas-form-layout"><div><p className="atlas-eyebrow">Start a conversation</p><h2 className="atlas-section-title">A useful first message is enough.</h2><p className="atlas-section-copy">Share the learner’s stage and preferred learning rhythm. The centre can guide you to a relevant next step.</p><div className="mt-7 space-y-3">{["Share the learner’s current stage", "Choose a preferred rhythm", "Receive a relevant response"].map(item => <p key={item} className="flex items-center gap-3 text-sm font-bold"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#e7f0eb] text-[#397563]"><Check size={15} /></span>{item}</p>)}</div></div><div className="atlas-form-wrap"><p className="atlas-eyebrow">Enquiry form</p><LeadForm /></div></div></section>

    <section className="atlas-section atlas-section-paper"><div className="compass-shell grid gap-8 lg:grid-cols-[.58fr_1.42fr]"><div><p className="atlas-eyebrow">Shared with permission</p><h2 className="atlas-section-title">Trust grows through real stories.</h2></div>{testimonials.data?.length ? <div className="grid gap-4 md:grid-cols-2">{testimonials.data.slice(0, 2).map(item => <article key={item.id} className="atlas-route-card"><div className="text-[#ef795b]">{Array.from({ length: Math.min(5, Math.max(1, item.rating)) }).map((_, star) => <Star key={star} className="inline" size={15} fill="currentColor" />)}</div><blockquote className="compass-display mt-8 text-3xl leading-tight">“{item.quote}”</blockquote><p className="mt-6 text-[10px] font-extrabold tracking-[.14em] text-[#397563] uppercase">{item.authorName} · {item.relation}</p></article>)}</div> : <div className="compass-empty !text-left"><CircleHelp className="text-[#397563]" size={28} /><h3 className="compass-display mt-5 text-3xl">Stories appear only with permission.</h3><p className="mt-3 max-w-xl text-sm leading-6 text-[#53657a]">When families choose to share a genuine experience, the centre can publish it here. Until then, ask a practical question about a learner’s next step.</p><Link href="/contact" className="atlas-button-secondary mt-6">Ask the centre <ArrowRight size={16} /></Link></div>}</div></section>

    <section className="pb-12 sm:pb-16"><div className="compass-shell grid gap-5 md:grid-cols-[1fr_.8fr]"><div className="rounded-[1.25rem] bg-[#10253e] p-7 text-white sm:p-9"><p className="atlas-eyebrow">Visit the centre</p><p className="atlas-section-title !mt-3 !text-white">Find Bilingual Idol in Setapak.</p><p className="mt-4 max-w-lg text-sm leading-7 text-white/70">StarParc Point, Jalan Genting Kelang, Kuala Lumpur. Come in with a language goal; leave with a clearer way forward.</p><Link href="/contact" className="atlas-button-primary mt-7">Plan a visit <MapPin size={16} /></Link></div><div className="atlas-media-panel"><img src="/manus-storage/bilingual-idol-contact-vignette_1b87f154.jpg" alt="A teacher welcoming a learner and parent at the learning centre" loading="lazy" /><span>Welcoming learning conversations</span></div></div></section>
  </div></PublicLayout>;
}
