import { ArrowRight, ArrowUpRight, BookOpen, Check, CircleHelp, Compass, GraduationCap, HeartHandshake, Languages, MapPin, Sparkles, Star } from "lucide-react";
import { Link } from "wouter";
import { LeadForm } from "@/components/LeadForm";
import { PublicLayout } from "@/components/PublicLayout";
import { trpc } from "@/lib/trpc";

const steps = [
  { number: "01", title: "Start with a real goal", copy: "Tell us the language, life stage, or confidence you want to build.", icon: Compass },
  { number: "02", title: "Choose a clear route", copy: "See confirmed programme details, practical timings, and the next useful action.", icon: BookOpen },
  { number: "03", title: "Keep progress visible", copy: "Return to materials, teacher support, payments, and reports from one learning room.", icon: HeartHandshake },
];

export default function Home() {
  const programs = trpc.content.publicPrograms.useQuery();
  const testimonials = trpc.content.publicTestimonials.useQuery();
  return <PublicLayout><div className="compass-page overflow-hidden">
    <section className="compass-paper compass-home-hero border-b border-[#ded4c2]"><div className="compass-shell grid h-full gap-10 lg:grid-cols-[1.05fr_.95fr] lg:items-center">
      <div className="max-w-2xl"><div className="flex items-center justify-between"><p className="compass-kicker">Bilingual Idol · Learning Compass</p><span className="compass-page-marker">01</span></div><h1 className="compass-display mt-8 text-5xl leading-[.9] text-[#10253e] sm:text-7xl lg:text-[5.8rem]">A clearer route to <em className="font-normal text-[#ef795b]">every</em> language goal.</h1><p className="mt-7 max-w-xl text-base leading-8 text-[#53657a] sm:text-lg">For children, teens, adults, and families building confidence in English, Bahasa Melayu, Mandarin, Arabic, Japanese, Korean, and more.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/enroll" className="compass-btn-primary">Enroll Now <ArrowUpRight size={17} /></Link><Link href="/programs" className="compass-btn-secondary">Learn More <ArrowRight size={17} /></Link></div><div className="mt-10 flex flex-wrap gap-x-5 gap-y-2 border-t border-[#ded4c2] pt-5 text-[10px] font-extrabold tracking-[.13em] text-[#397563] uppercase"><span>English</span><span>Bahasa Melayu</span><span>中文</span><span>العربية</span><span>日本語</span><span>한국어</span></div></div>
      <div className="compass-foundation p-6 sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="compass-kicker">Your learning compass</p><h2 className="compass-display mt-4 text-4xl leading-tight">One place to choose the next right step.</h2></div><Sparkles className="text-[#ef795b]" /></div><div className="mt-8 divide-y divide-[#ded4c2] border-y border-[#ded4c2]">{steps.map(({ number, title, copy, icon: Icon }) => <div key={number} className="grid grid-cols-[2.5rem_1fr_auto] gap-3 py-5"><span className="font-display text-2xl text-[#ef795b]">{number}</span><div><p className="font-bold text-[#10253e]">{title}</p><p className="mt-1 text-sm leading-6 text-[#607084]">{copy}</p></div><Icon className="mt-1 text-[#397563]" size={19} /></div>)}</div><Link href="/learning" className="compass-btn-primary mt-8 w-full">Open the learning hub <ArrowUpRight size={16} /></Link></div>
    </div></section>

    <section className="border-b border-[#ded4c2] bg-white"><div className="compass-shell grid md:grid-cols-3"><div className="border-b border-[#ded4c2] py-7 md:border-b-0 md:border-r md:pr-7"><p className="text-[10px] font-extrabold tracking-[.14em] text-[#397563] uppercase">Established</p><p className="compass-display mt-2 text-3xl">Since 2008</p></div><div className="border-b border-[#ded4c2] py-7 md:border-b-0 md:border-r md:px-7"><p className="text-[10px] font-extrabold tracking-[.14em] text-[#397563] uppercase">Based in</p><p className="compass-display mt-2 text-3xl">Setapak, Kuala Lumpur</p></div><div className="py-7 md:pl-7"><p className="text-[10px] font-extrabold tracking-[.14em] text-[#397563] uppercase">Built for</p><p className="compass-display mt-2 text-3xl">Practical confidence</p></div></div></section>

    <section className="compass-grid py-20 sm:py-28"><div className="compass-shell"><div className="grid gap-8 lg:grid-cols-[.68fr_1.32fr]"><div><p className="compass-kicker">Programme finder</p><h2 className="compass-display mt-5 text-5xl leading-[.94] sm:text-6xl">Choose a pathway with the right details in view.</h2><p className="mt-6 max-w-sm text-base leading-7 text-[#53657a]">Search confirmed programmes by language, level, age group, schedule, and learning goal. If you are unsure, start a conversation instead.</p><Link href="/programs" className="compass-btn-secondary mt-8">Explore programmes <ArrowRight size={17} /></Link></div><div>{programs.isLoading ? <div className="grid gap-4 sm:grid-cols-2">{[1, 2, 3, 4].map(item => <div key={item} className="skeleton-shimmer h-64 rounded-2xl" />)}</div> : programs.data?.length ? <div className="grid gap-4 sm:grid-cols-2">{programs.data.slice(0, 4).map(program => <Link key={program.slug} href={`/programs/${program.slug}`} className="compass-card group block min-h-64 p-6"><div className="flex items-center justify-between"><span className="rounded-full bg-[#e7f0eb] px-3 py-1 text-[10px] font-extrabold tracking-[.12em] text-[#397563] uppercase">{program.language}</span><ArrowUpRight className="text-[#397563] transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" size={20} /></div><h3 className="compass-display mt-10 text-4xl leading-tight">{program.title}</h3><p className="mt-4 line-clamp-3 text-sm leading-6 text-[#53657a]">{program.description}</p><p className="mt-6 text-xs font-extrabold tracking-[.1em] text-[#397563] uppercase">{program.ageGroup} · {program.level}</p></Link>)}</div> : <div className="compass-empty"><Languages className="mx-auto text-[#397563]" size={30} /><h3 className="compass-display mt-4 text-3xl">Confirmed programme details are being prepared.</h3><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-[#53657a]">The centre can still help you choose a relevant next step while verified programme details are added.</p><Link href="/contact" className="compass-btn-secondary mt-6">Ask for guidance <ArrowRight size={16} /></Link></div>}</div></div></div></section>

    <section className="bg-[#10253e] py-20 text-white sm:py-24"><div className="compass-shell"><div className="grid gap-7 lg:grid-cols-[.9fr_1.1fr]"><div><p className="compass-kicker !text-[#a7c6b8]">How it works</p><h2 className="compass-display mt-5 text-5xl leading-[.95] sm:text-6xl">Less searching. More learning.</h2></div><p className="max-w-xl self-end text-base leading-7 text-white/70">The platform is arranged around the actions families and learners need: understanding what is next, completing it, and returning without losing context.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3">{steps.map(({ number, title, copy, icon: Icon }) => <article key={number} className="border-t border-white/20 pt-6"><div className="flex items-center justify-between"><span className="font-display text-4xl text-[#f3b59f]">{number}</span><Icon className="text-[#a7c6b8]" size={21} /></div><h3 className="compass-display mt-8 text-3xl">{title}</h3><p className="mt-3 text-sm leading-6 text-white/65">{copy}</p></article>)}</div></div></section>

    <section className="py-20 sm:py-28"><div className="compass-shell grid gap-10 lg:grid-cols-[.72fr_1.28fr]"><div><p className="compass-kicker">Start a conversation</p><h2 className="compass-display mt-5 text-5xl leading-[.94] sm:text-6xl">Tell us where the learner wants to go.</h2><p className="mt-6 max-w-sm text-base leading-7 text-[#53657a]">A clear first message helps the centre recommend the next route. You do not need to select a programme before asking for guidance.</p><div className="mt-9 space-y-3">{["Share the learner’s current stage", "Choose a preferred rhythm", "Receive a relevant response"].map(item => <p key={item} className="flex items-center gap-3 text-sm font-bold"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#e7f0eb] text-[#397563]"><Check size={15} /></span>{item}</p>)}</div></div><div className="compass-form"><p className="compass-kicker">Enquiry form</p><LeadForm /></div></div></section>

    <section className="border-y border-[#ded4c2] bg-[#f4eddd] py-20"><div className="compass-shell grid gap-8 lg:grid-cols-[.58fr_1.42fr]"><div><p className="compass-kicker">Shared with permission</p><h2 className="compass-display mt-5 text-5xl leading-[.94]">Trust grows through real stories.</h2></div>{testimonials.data?.length ? <div className="grid gap-4 md:grid-cols-2">{testimonials.data.slice(0, 2).map(item => <article key={item.id} className="compass-card p-7"><div className="text-[#ef795b]">{Array.from({ length: Math.min(5, Math.max(1, item.rating)) }).map((_, star) => <Star key={star} className="inline" size={15} fill="currentColor" />)}</div><blockquote className="compass-display mt-6 text-3xl leading-tight">“{item.quote}”</blockquote><p className="mt-6 text-[10px] font-extrabold tracking-[.14em] text-[#397563] uppercase">{item.authorName} · {item.relation}</p></article>)}</div> : <div className="compass-empty !text-left"><CircleHelp className="text-[#397563]" size={28} /><h3 className="compass-display mt-5 text-3xl">Stories appear only with permission.</h3><p className="mt-3 max-w-xl text-sm leading-6 text-[#53657a]">When families choose to share a genuine experience, the centre can publish it here. Until then, ask a practical question about a learner’s next step.</p><Link href="/contact" className="compass-btn-secondary mt-6">Ask the centre <ArrowRight size={16} /></Link></div>}</div></section>

    <section className="py-12 sm:py-16"><div className="compass-shell compass-ink grid gap-6 rounded-2xl p-7 sm:grid-cols-[auto_1fr_auto] sm:items-center"><span className="grid h-14 w-14 place-items-center rounded-full bg-[#ef795b] text-[#10253e]"><MapPin size={24} /></span><div><p className="text-[10px] font-extrabold tracking-[.14em] text-[#a7c6b8] uppercase">Visit the centre</p><p className="compass-display mt-2 text-3xl">Find Bilingual Idol in Setapak.</p><p className="mt-1 text-sm text-white/65">StarParc Point, Jalan Genting Kelang, Kuala Lumpur.</p></div><Link href="/contact" className="compass-btn-secondary">Plan a visit <ArrowUpRight size={16} /></Link></div></section>
  </div></PublicLayout>;
}
