import { ArrowRight, ArrowUpRight, CalendarDays, Check, CircleHelp, GraduationCap, HeartHandshake, Languages, MapPin, Sparkles, Star } from "lucide-react";
import { Link } from "wouter";
import { LeadForm } from "@/components/LeadForm";
import { PublicLayout } from "@/components/PublicLayout";
import { trpc } from "@/lib/trpc";

const principles = [
  { icon: Languages, title: "Many languages, one community", body: "Explore English, Bahasa Melayu, Mandarin, Arabic, Japanese, Korean, and more in a welcoming learning environment." },
  { icon: HeartHandshake, title: "Designed around the learner", body: "Every conversation starts with your goals, your current confidence, and the support you need next." },
  { icon: GraduationCap, title: "A confident next step", body: "We help learners build the language skills that support school, career, daily life, and new opportunities." },
];

export default function Home() {
  const programs = trpc.content.publicPrograms.useQuery();
  const testimonials = trpc.content.publicTestimonials.useQuery();
  return <PublicLayout>
    <section className="hero-grid relative isolate bg-[#10253e] py-16 text-white sm:py-20 lg:py-28">
      <div className="hero-glow absolute -right-16 top-10 h-64 w-64 rounded-full opacity-70 sm:right-[18%] sm:top-0 sm:h-96 sm:w-96" />
      <div className="absolute left-[7%] top-[18%] h-24 w-24 rounded-full border border-white/15 sm:h-36 sm:w-36" /><div className="absolute bottom-12 right-[6%] h-20 w-20 rounded-full border border-[#f3b59f]/45" />
      <div className="site-container relative grid items-end gap-12 lg:grid-cols-[1.15fr_.85fr]">
        <div className="max-w-3xl"><p className="rise-in eyebrow !text-[#a7c6b8]"><span className="sr-only">Bilingual Idol</span> Language, belonging, possibility</p><h1 className="rise-in-delay mt-5 font-display text-5xl leading-[.98] tracking-[-.035em] sm:text-6xl lg:text-8xl">Learn a language.<br /><em className="font-normal text-[#f3b59f]">Find your voice.</em></h1><p className="rise-in-delay-2 mt-7 max-w-xl text-base leading-7 text-white/74 sm:text-lg">Learn with confidence — <span lang="ms">belajar dengan yakin</span>. We create thoughtful language pathways for children, teens, adults, and professionals in Kuala Lumpur.</p><div className="rise-in-delay-2 mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/enroll" className="pressable inline-flex items-center justify-center gap-2 rounded-full bg-[#f07e5d] px-6 py-4 text-sm font-extrabold text-[#10253e] shadow-[0_12px_32px_rgba(4,15,29,.28)] hover:bg-[#f7c0ac]">Enroll Now <ArrowUpRight size={17} /></Link><Link href="/programs" className="pressable inline-flex items-center justify-center gap-2 rounded-full border border-white/25 bg-white/5 px-6 py-4 text-sm font-extrabold text-white hover:bg-white hover:text-[#10253e]">Learn More <ArrowRight size={17} /></Link></div><p className="mt-5 text-xs font-bold tracking-[.08em] text-white/46 uppercase">English · Bahasa Melayu · 中文 · العربية · 日本語 · 한국어</p></div>
        <div className="hero-orbit justify-self-center lg:justify-self-end"><div className="glass-panel relative w-[min(100%,25rem)] rounded-[2rem] p-5 sm:p-7"><div className="absolute -right-3 -top-3 grid h-12 w-12 place-items-center rounded-full bg-[#a7c6b8] text-[#10253e] shadow-lg"><Sparkles size={20} /></div><p className="text-xs font-extrabold tracking-[.14em] text-[#a7c6b8] uppercase">A gentler way to begin</p><div className="mt-5 rounded-2xl bg-white/9 p-5"><p className="font-display text-3xl leading-none">“Hello.”</p><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><span className="rounded-lg bg-white/8 px-3 py-2">Hello</span><span className="rounded-lg bg-white/8 px-3 py-2">Halo</span><span className="rounded-lg bg-white/8 px-3 py-2">你好</span><span className="rounded-lg bg-white/8 px-3 py-2">مرحبا</span></div></div><div className="mt-5 flex items-center justify-between border-t border-white/12 pt-5"><div><p className="text-xs text-white/55">Your first step</p><p className="mt-1 text-sm font-bold">Tell us about your goal</p></div><Link href="/contact" className="grid h-10 w-10 place-items-center rounded-full bg-white text-[#10253e] hover:bg-[#f07e5d]" aria-label="Contact Bilingual Idol"><ArrowUpRight size={17} /></Link></div></div></div>
      </div>
    </section>
    <section className="border-b border-[#e8dcc9] bg-[#f7f1e8]"><div className="site-container grid gap-px bg-[#e2d5c4] sm:grid-cols-3"><div className="bg-[#f7f1e8] p-6"><p className="text-xs font-extrabold tracking-[.12em] text-[#5e8c7b] uppercase">Established</p><p className="mt-2 font-display text-3xl text-[#10253e]">Since 2008</p></div><div className="bg-[#f7f1e8] p-6"><p className="text-xs font-extrabold tracking-[.12em] text-[#5e8c7b] uppercase">Based in</p><p className="mt-2 font-display text-3xl text-[#10253e]">Kuala Lumpur</p></div><div className="bg-[#f7f1e8] p-6"><p className="text-xs font-extrabold tracking-[.12em] text-[#5e8c7b] uppercase">Built for</p><p className="mt-2 font-display text-3xl text-[#10253e]">Every learner</p></div></div></section>
    <section className="surface-grid py-20 sm:py-28"><div className="site-container"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Your path starts here</p><h2 className="display-balance mt-4 font-display text-4xl leading-[1.03] text-[#10253e] sm:text-5xl">A programme for the way you want to grow.</h2></div><p className="self-end max-w-xl text-base leading-7 text-[#53657a]">From a child’s first English words to workplace-ready conversations, our programmes can be explored by language, age group, and learning goal.</p></div>{programs.isLoading ? <div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{[1,2,3].map(item => <div key={item} className="h-60 animate-pulse rounded-[1.3rem] bg-white" />)}</div> : <><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{(programs.data ?? []).slice(0, 6).map(program => <Link key={program.slug} href={`/programs/${program.slug}`} className="group rounded-[1.3rem] border border-[#e1d5c4] bg-white p-5 shadow-[0_7px_24px_rgba(16,37,62,.055)] hover:-translate-y-1 hover:border-[#f07e5d]/60 hover:shadow-[0_20px_40px_rgba(16,37,62,.12)]"><div className="flex items-start justify-between gap-3"><span className="rounded-full bg-[#eff5f1] px-3 py-1 text-[10px] font-extrabold tracking-[.1em] text-[#3f7564] uppercase">{program.language}</span><span className="grid h-8 w-8 place-items-center rounded-full bg-[#f7f1e8] text-[#10253e] group-hover:bg-[#f07e5d]"><ArrowUpRight size={15} /></span></div><h3 className="mt-9 font-display text-3xl leading-none text-[#10253e]">{program.title}</h3><p className="mt-4 text-sm leading-6 text-[#5b6d80]">{program.description}</p><p className="mt-5 text-xs font-bold text-[#5e8c7b]">{program.ageGroup}</p></Link>)}</div>{programs.data?.length === 0 && <div className="mt-8 rounded-[1.4rem] border border-dashed border-[#cbbba4] bg-[#fbf8f2] p-7 text-center"><p className="font-display text-3xl text-[#10253e]">The confirmed catalogue is being prepared.</p><p className="mt-2 text-sm text-[#53657a]">Our team can still help you choose a suitable language pathway.</p></div>}</>}<Link href="/programs" className="pressable mt-8 inline-flex items-center gap-2 text-sm font-extrabold text-[#10253e] hover:text-[#f07e5d]">View all programmes <ArrowRight size={17} /></Link></div></section>
    <section className="bg-[#10253e] py-20 text-white sm:py-28"><div className="site-container"><p className="eyebrow !text-[#a7c6b8]">Why Bilingual Idol</p><div className="mt-4 flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><h2 className="display-balance max-w-2xl font-display text-4xl leading-[1.02] sm:text-5xl">Language learning should feel <em className="font-normal text-[#f3b59f]">possible</em> from day one.</h2><Link href="/about" className="pressable inline-flex shrink-0 items-center gap-2 rounded-full border border-white/25 px-5 py-3 text-sm font-bold hover:bg-white hover:text-[#10253e]">Meet the centre <ArrowUpRight size={16} /></Link></div><div className="mt-12 grid gap-5 md:grid-cols-3">{principles.map(({ icon: Icon, title, body }) => <article key={title} className="rounded-[1.35rem] border border-white/12 bg-white/[.055] p-6"><Icon className="text-[#f3b59f]" size={26} /><h3 className="mt-8 font-display text-3xl">{title}</h3><p className="mt-3 text-sm leading-6 text-white/65">{body}</p></article>)}</div></div></section>
    <section className="py-20 sm:py-28"><div className="site-container grid items-start gap-10 lg:grid-cols-[.9fr_1.1fr]"><div className="lg:sticky lg:top-28"><p className="eyebrow">A conversation, not a commitment</p><h2 className="display-balance mt-4 font-display text-4xl leading-[1.02] text-[#10253e] sm:text-5xl">Let’s find the right next step.</h2><p className="mt-5 max-w-md text-base leading-7 text-[#53657a]">Share your learner’s age, goals, and preferred schedule. Our team can help you decide where to begin.</p><div className="mt-8 grid gap-3 text-sm font-semibold text-[#29415b]"><p className="flex items-center gap-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#eff5f1] text-[#5e8c7b]"><Check size={15} /></span> Choose a programme or ask for guidance</p><p className="flex items-center gap-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#eff5f1] text-[#5e8c7b]"><Check size={15} /></span> Tell us when learning works best</p><p className="flex items-center gap-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#eff5f1] text-[#5e8c7b]"><Check size={15} /></span> Receive a thoughtful follow-up</p></div></div><LeadForm /></div></section>
    <section className="border-y border-[#e8dcc9] bg-[#f7f1e8] py-16"><div className="site-container"><div className="grid gap-8 md:grid-cols-[.9fr_1.1fr]"><div><p className="eyebrow">Shared experiences</p><h2 className="mt-4 font-display text-4xl leading-[1.04] text-[#10253e]">Stories are best shared with permission.</h2></div>{testimonials.data?.length ? <div className="grid gap-4">{testimonials.data.slice(0, 2).map(item => <article key={item.id} className="rounded-[1.5rem] border border-[#e1d5c4] bg-white p-6"><div className="flex gap-1 text-[#f07e5d]" aria-label={`${item.rating} out of 5 stars`}>{Array.from({ length: Math.min(5, Math.max(1, item.rating)) }).map((_, index) => <Star key={index} size={15} fill="currentColor" />)}</div><blockquote className="mt-4 font-display text-2xl leading-tight text-[#10253e]">“{item.quote}”</blockquote><p className="mt-4 text-xs font-extrabold tracking-[.1em] text-[#5e8c7b] uppercase">{item.authorName} · {item.relation}</p></article>)}</div> : <div className="rounded-[1.5rem] border border-dashed border-[#cbbba4] bg-[#fbf8f2] p-7"><CircleHelp className="text-[#5e8c7b]" size={27} /><p className="mt-4 text-sm leading-7 text-[#53657a]">Approved parent and student reviews will be published here by the centre. Until then, you can ask our team about the learning experience that may be right for you.</p><Link href="/contact" className="mt-5 inline-flex items-center gap-2 text-sm font-extrabold text-[#10253e] hover:text-[#f07e5d]">Ask a question <ArrowRight size={16} /></Link></div>}</div></div></section>
    <section className="py-16"><div className="site-container flex flex-col gap-5 rounded-[1.7rem] bg-[#e7f0eb] p-7 sm:p-10 md:flex-row md:items-center md:justify-between"><div className="flex items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-white text-[#5e8c7b]"><MapPin size={22} /></span><div><p className="font-display text-3xl text-[#10253e]">Visit us in Setapak</p><p className="mt-1 text-sm leading-6 text-[#53657a]">Meet us at StarParc Point, Jalan Genting Kelang, Kuala Lumpur.</p></div></div><Link href="/contact" className="pressable inline-flex items-center justify-center gap-2 rounded-full bg-[#10253e] px-5 py-3 text-sm font-extrabold text-white hover:bg-[#f07e5d] hover:text-[#10253e]">Plan your visit <CalendarDays size={17} /></Link></div></section>
  </PublicLayout>;
}
