import { CalendarDays, Megaphone, Newspaper, PartyPopper } from "lucide-react";
import { PublicLayout } from "@/components/PublicLayout";
import { trpc } from "@/lib/trpc";

const categoryIcon = { announcement: Megaphone, event: CalendarDays, holiday: PartyPopper };
export default function News() {
  const announcements = trpc.content.publicAnnouncements.useQuery();
  return <PublicLayout><div className="compass-page"><section className="compass-paper"><div className="compass-shell grid gap-8 py-16 sm:py-20 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="compass-kicker">Announcements & news</p><h1 className="compass-display mt-5 max-w-4xl text-5xl leading-[.95] sm:text-6xl">The centre notice board, kept <em className="font-normal text-[#ef795b]">clear.</em></h1><p className="mt-6 max-w-2xl text-base leading-7 text-[#53657a]">Updates, events, and holiday notices appear here after the centre is ready to share verified information.</p></div><span className="compass-page-marker">04</span></div></section><section className="compass-grid py-16 sm:py-20"><div className="compass-shell">{announcements.isLoading && <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{[1, 2, 3].map(item => <div key={item} className="skeleton-shimmer h-64 rounded-2xl" />)}</div>}{announcements.error && <div className="compass-status-error p-7"><p className="compass-display text-3xl text-[#10253e]">Updates are temporarily unavailable.</p><p className="mt-2 text-sm leading-6">Please check back shortly or contact the centre directly.</p></div>}{announcements.data && announcements.data.length > 0 && <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{announcements.data.map((item, index) => { const Icon = categoryIcon[item.category]; return <article key={item.id} className="compass-card p-6"><div className="flex items-start justify-between"><span className={`grid h-10 w-10 place-items-center rounded-xl ${index % 3 === 1 ? "bg-[#f4eddd] text-[#a34732]" : "bg-[#e7f0eb] text-[#397563]"}`}><Icon size={18} /></span><p className="rounded-full border border-[#ded4c2] px-3 py-1 text-[10px] font-extrabold tracking-[.1em] text-[#53657a] uppercase">{item.category}</p></div><h2 className="compass-display mt-8 text-3xl leading-tight">{item.title}</h2><p className="mt-3 text-sm leading-6 text-[#5b6d80]">{item.excerpt}</p><p className="mt-6 border-t border-[#eee4d7] pt-4 text-xs font-bold text-[#708098]">{item.publishedAt ? new Date(item.publishedAt).toLocaleDateString() : "Published by the centre"}</p></article>; })}</div>}{announcements.data && announcements.data.length === 0 && <div className="compass-empty"><span className="mx-auto grid h-14 w-14 place-items-center rounded-xl bg-[#e7f0eb] text-[#397563]"><Newspaper size={24} /></span><h2 className="compass-display mt-5 text-4xl">No notices are published right now.</h2><p className="mx-auto mt-3 max-w-lg text-sm leading-7 text-[#53657a]">This board will share the centre’s verified news, events, and holiday notices after publication. No unconfirmed updates are shown.</p></div>}</div></section></div></PublicLayout>;
}
