import { ArrowLeft, ArrowRight, CalendarClock, Check, Clock3, GraduationCap, Landmark, WalletCards } from "lucide-react";
import { Link, useRoute } from "wouter";
import { PublicLayout } from "@/components/PublicLayout";
import { trpc } from "@/lib/trpc";

export default function ProgramDetail() {
  const [, params] = useRoute("/programs/:slug");
  const record = trpc.content.publicProgram.useQuery({ slug: params?.slug ?? "" }, { enabled: Boolean(params?.slug) });
  const program = record.data;
  if (record.isLoading) return <PublicLayout><div className="compass-shell py-24"><div className="skeleton-shimmer h-72 rounded-2xl" /></div></PublicLayout>;
  if (!program) return <PublicLayout><div className="compass-shell py-24"><div className="compass-empty"><p className="compass-display text-4xl">Programme details are not available yet.</p><p className="mt-3 text-sm leading-6 text-[#53657a]">The course may still be awaiting confirmation by the centre.</p><Link href="/programs" className="compass-btn-secondary mt-6"><ArrowLeft size={16} /> Browse programmes</Link></div></div></PublicLayout>;
  const facts = [{ icon: GraduationCap, label: "Best for", value: program.ageGroup }, { icon: Landmark, label: "Level", value: program.level }, { icon: Clock3, label: "Duration", value: program.duration }, { icon: CalendarClock, label: "Schedule", value: program.schedule }, { icon: WalletCards, label: "Fees", value: program.fees }];
  const confirmationPoints = ["Programme level and intended learner group", "Confirmed schedule and fee information", "A next-step conversation with the centre"];
  return <PublicLayout><div className="compass-page"><section className="compass-ink"><div className="compass-shell py-12 sm:py-16"><Link href="/programs" className="inline-flex items-center gap-2 text-sm font-extrabold text-[#a7c6b8] hover:text-white"><ArrowLeft size={16} /> All programmes</Link><div className="mt-10 grid gap-8 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><p className="compass-kicker !text-[#a7c6b8]">{program.language} programme</p><h1 className="compass-display mt-5 text-5xl leading-[.95] sm:text-7xl">{program.title}</h1><p className="mt-6 max-w-2xl text-base leading-7 text-white/70">{program.description}</p></div><div className="rounded-2xl border border-white/15 bg-white/7 p-6"><p className="text-[10px] font-extrabold tracking-[.13em] text-[#f3b59f] uppercase">Next step</p><p className="mt-3 text-sm leading-7 text-white/75">Share the learner’s current level and goal. The centre will help confirm whether this is the right route.</p><Link href="/enroll" className="compass-btn-primary mt-6 w-full !bg-[#ef795b] !text-[#10253e] hover:!bg-white">Enroll Now <ArrowRight size={16} /></Link></div></div></div></section><section className="compass-grid py-16 sm:py-20"><div className="compass-shell grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><aside><p className="compass-kicker">Programme at a glance</p><div className="mt-6 grid gap-3">{facts.map(({ icon: Icon, label, value }) => <div key={label} className="compass-card flex gap-3 p-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-[#e7f0eb] text-[#397563]"><Icon size={18} /></span><div><p className="text-[10px] font-extrabold tracking-[.1em] text-[#708098] uppercase">{label}</p><p className="mt-1 text-sm font-bold leading-5 text-[#29415b]">{value}</p></div></div>)}</div></aside><div><p className="compass-kicker">Before you choose</p><h2 className="compass-display mt-5 text-5xl leading-[.96]">Clarity before commitment.</h2><p className="mt-6 max-w-2xl text-base leading-7 text-[#53657a]">The centre can confirm availability, course structure, and the most relevant entry point based on a learner’s goals and experience.</p><div className="mt-8 grid gap-3">{confirmationPoints.map(point => <p key={point} className="flex items-start gap-3 rounded-xl bg-[#e7f0eb] p-4 text-sm font-bold text-[#29415b]"><span className="mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-[#397563] text-white"><Check size={13} /></span>{point}</p>)}</div><div className="compass-foundation mt-10 p-6"><p className="compass-kicker">Need help choosing?</p><h3 className="compass-display mt-4 text-3xl">Talk through the right starting point.</h3><p className="mt-3 max-w-xl text-sm leading-6 text-[#53657a]">Ask about age group, current level, language goal, and preferred schedule before you decide.</p><Link href="/contact" className="compass-btn-primary mt-6">Ask about this programme <ArrowRight size={16} /></Link></div></div></div></section></div></PublicLayout>;
}
